title: >
  <p align="center"> Nicholas J. Wilson </p>

logo: "/assets/images/logo_mar25.png?raw=true"

description: >
  <p align="center">
  <a href="https://www.novasbe.unl.pt/en/programs/phds/phd-in-economics-finance/overview/"><img src="https://njwsn.github.io/assets/images/nova_full2.png" width="231px" height="32px"></a>
  <a href="https://www.otherwiseresearch.org/"><img src="https://njwsn.github.io/assets/images/otherwise_logo.png" width="181px" height="40px"></a><br>
  </p>
  
  <p align="center">
  <a href="mailto:nj.wilson@outlook.com"><i class="fa-solid fa-envelope fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://njwsn.github.io/assets/NW_CV_mar25.pdf"><i class="fa-solid fa-circle-info fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://x.com/nj_wsn"><i class="fa-brands fa-square-x-twitter fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://www.linkedin.com/in/njwsn/"><i class="fa-brands fa-linkedin fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://orcid.org/0009-0006-3680-2015"><i class="fa-brands fa-orcid fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://scholar.google.com/citations?user=Nj_UmX0AAAAJ&hl=en"><i class="fa-brands fa-google-scholar fa-xl"></i></a>
  </p>
  
  <p align="center">
  Economist and research consultant: development, fragility, political economy, state capacity, East Africa. </br> 
  </p>
  
  <p align="center">
  PhD Student @ <a href="https://www.novasbe.unl.pt/en/programs/phds/phd-in-economics-finance/overview">Nova SBE</a>, affiliated with <a href="https://novafrica.org/phdcandidates/">NOVAFRICA</a>.</br>
  Technical Advisor @ <a href="https://www.otherwiseresearch.org/">OTHERwise Research</a>.</br>
  Mentor @ <a href="https://malengo.org/">Malengo</a>, Uganda-Germany Program.</br>
  </p>

  <p align="center">
  Extensive field experience in Kenya and South Sudan.</br> 
  Graduate of LMU Munich (MSc) and Warwick (BSc).
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
