title: >
  <p align="center"> Nicholas J. Wilson </p>

logo: "/assets/images/logo_300hdr.png?raw=true"

description: >
  <p align="center">
  <a href="https://www.novasbe.unl.pt/en/programs/phds/phd-in-economics-finance/phd-students"><img src="https://njwsn.github.io/assets/images/nova_full2.png" width="220px" height="30px"></a><br>
  <! -- <a href="https://www.forcierconsulting.com/"><img src="https://njwsn.github.io/assets/images/forcier_logo.png" width="152px" height="30px"></a><br> -->
  </p>
  
  <p align="center">
  <a href="mailto:nj.wilson@outlook.com"><i class="fa-solid fa-envelope fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://njwsn.github.io/assets/NW_CV_Oct24.pdf"><i class="fa-solid fa-circle-info fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://x.com/nj_wsn"><i class="fa-brands fa-square-x-twitter fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://www.linkedin.com/in/njwsn/"><i class="fa-brands fa-linkedin fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://orcid.org/0009-0006-3680-2015"><i class="fa-brands fa-orcid fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://scholar.google.com/citations?user=Nj_UmX0AAAAJ&hl=en"><i class="fa-brands fa-google-scholar fa-xl"></i></a>
  </p>
  
  <p align="center">
  Economist and research consultant: conflict, fragility, development, political economy, East Africa. </br> 
  </p>
  
  <p align="center">
  PhD Student @ Nova SBE.</br>
  <! -- Research Manager @ Forcier Consulting. -->
  </p>

  <p align="center">
  Extensive field experience in Kenya and South Sudan. Graduated from LMU Munich (MSc) and Warwick (BSc).
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # my Google Analytics tracking ID
