title: >
  <p align="center"> <br>
  Nicholas J. Wilson </p>

logo: "/assets/images/logo_300hdr.png?raw=true"

description: >
  <p align="center">
  <a href="mailto:nj.wilson@outlook.com"><i class="fa-solid fa-envelope fa-xl"></i></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://njwsn.github.io/assets/NW_CV_May24.pdf"><i class="fa-solid fa-circle-info fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://x.com/nj_wsn"><i class="fa-brands fa-square-x-twitter fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://www.linkedin.com/in/njwsn/"><i class="fa-brands fa-linkedin fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://orcid.org/0009-0006-3680-2015"><i class="fa-brands fa-orcid fa-xl"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://scholar.google.com/citations?user=Nj_UmX0AAAAJ&hl=en"><i class="fa-brands fa-google-scholar fa-xl"></i></a>
  </p>
  
  <p align="center">
  Economist researching development and political economy across Africa and the Middle East.
  </p>

  <p align="center">
  Focus on studying fragility: attitudes, norms, policies, and social institutions that promote or preclude stability. 
  </p>

  <p align="center">
  Extensive experience in Kenya, South Sudan, Turkey. Graduated from LMU Munich (MSc) and Warwick (BSc).
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
