title: Nicholas J. Wilson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Economist and research consultant, studying development and political economy in East Africa and the Near East.
  <br><br>
  Focus on fragility: understanding norms, beliefs, attitudes, and institutions that promote or preclude stability. 
  <br><br>
  RM @ Forcier Consulting, South Sudan. Formerly UNDP Kenya, OC&C London.
  <br><br>
  [<a href="https://github.com/njwsn/njwsn.github.io/raw/1ea4377d85e01a3f172d0a794b297beaf5639dbd/assets/NW_CV_May24.pdf">CV</a>]
  [<a href="https://twitter.com/nj_wsn">Twitter</a>] [<a href="https://www.linkedin.com/in/njwsn/">LinkedIn</a>]
  [<a href="https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=4891811">SSRN</a>]
  [<a href="https://scholar.google.com/citations?user=Nj_UmX0AAAAJ&hl=en">GScholar</a>]       
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
